### ISSUE TITLE
Fix your README.md please

### ISSUE THREAD

**Issue by Ashrindy** [creamsensation/gox#1]
Hello,
I think you made a slight typo in your very basic README.md, I don't think you have English studied well. In the part where you say: "If you love Go, as I am...", it should be "If you love Go, as I ***do***.."! **Please fix it otherwise I will have a heart attack!**
Thank you!

Best regards, Ashrindy.

**Comment by daarxwalker** [comment]
It'll be fixed in the next release.
We are only humans 😇
